---
- name: ensure add-apt-repositories is present
  # sudo apt-get install software-properties-common
  become: true
  package: name=software-properties-common state=present

- name: Certbot | Add certbot PPAs
  become: true
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "ppa:certbot/certbot"
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version is version_compare('20.04', '<')

- name: Certbot | Install package
  become: true
  apt:
    name: "{{ certbot_package }}"
    state: present
